server:
  port: 8090


knife4j:
  # 开启增强模式，对knife4j的接口测试以及文档编写进行一定个性化设置
  enable: true
  setting:
    language: zh_cn
    enable-open-api: true
  basic:
    enable: false # 是否设置BasicHttp功能 开启则需设置进入Knife4j的账号密码
